spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false
  sql:
    init:
      mode: always

jwt:
  secret: ${JWT_SECRET}
token:
  expire:
    time:
      access: ${TOKEN_EXPIRE_TIME_ACCESS}
      refresh: ${TOKEN_EXPIRE_TIME_REFRESH}

oauth:
  kakao:
    rest-api-key: ${OAUTH_KAKAO_REST_API_KEY}
    redirect-url: ${OAUTH_KAKAO_REDIRECT_URL}

aws:
  s3:
    accessKey: ${S3_ACCESS_KEY}
    secretKey: ${S3_SECRET_KEY}